# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4349fbb2072f34ea5984ba6b73767e9fcb4ab19f9509cf2fafb0ab6024f4c32fb86def2a56f028dd29de21caaf4a10f62dfa4578b7ca53701c14a2ad8d02479

test:
  secret_key_base: 5cd571d80f66fd4689ed0ee69330428d8d9cfdc164ee8ac9aac59f1ac97c3f30463bdd89f445da0a2f771706f8f5573639deb3d164920eaca892e214b6bf6e65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
